### ISSUE TITLE
Redux 101

### ISSUE THREAD

**Issue by mishelashala** [chilangodev/platicas#16]
# Redux 101

What is Redux and how it works?
## Summary
1. Single Source of Truth
2. Actions [creators]
3. Reducers
4. Stores
## Outline
1. Single Source of Trurh
   - One state tree
   - Immutable data structure
   - Globally Available
2. Actions [creatos]
   - What is an action?
   - How to create them?
   - Why?
3. Reducers
   - What is a reducer?
   - How to implement one?
4. One global store
   - Using redux.createStore
   - Dispatch events
   - Subscribe to store
## Bio

``` yaml
name: Michell Ayala
url: @mishelashala
pic: https://pbs.twimg.com/profile_images/747323729890287616/v6QpVXRO.jpg
bio: JavaScript Developer
```
